language: node_js
node_js:
 — “7”
script:
 — echo "Deploying cloud functions...”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project $PROJECT_ID — token $FIREBASE_TOKEN.